[pytest]
markers =
    integration: marks integration tests
    regression: marks regression tests
    smoke: marks smoke tests
    smoke2: marks smoke tests 2
    unitT2: marks unitT2 tests

;addopts = -v --html=reports/report.html --self-contained-html --template=html1/index.html --report=htmlreport/report.html
;addopts = -v --html=reports/report.html --self-contained-html
;addopts = -v -p no:html_reporter --html=reports/report.html --self-contained-html
